### ISSUE TITLE
Having something error

### ISSUE THREAD

**Issue by sam21456789** [paslandau/pagerank#1]
Failed to clone git@github.com:paslandu/io-utility.git, git was not found, check that it is installed and in your PATH env

**Comment by paslandau** [comment]
Hey @sam21456789 
can you post your `composer.json`?

Did you include

```
  "repositories": [ { "type": "composer", "url": "http://packages.myseosolution.de/"} 
```

?

**Comment by sam21456789** [comment]
{
  "name": "paslandau/pagerank",
  "license": "MIT",
  "description": "Calculating the PageRank of nodes in a linked graph",
  "authors": [
    {
      "name": "Pascal Landau",
      "email": "kontakt@myseosolution.de",
      "homepage": "http://www.myseosolution.de",
      "role": "Developer"
    }
  ],
  "autoload": {
    "psr-4": {
      "paslandau\PageRank\": "src/"
    }
  },
  "repositories": [
    {
      "type": "composer",
      "url": "http://packages.myseosolution.de/"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "php": "~5.5",
    "psr/log": "~1",
    "monolog/monolog": "~1",
    "paslandau/io-utility": "^0.1.2"
  },
  "require-dev": {
    "phpunit/phpunit": "~4"
  }
}

This is what my composer.json look like.   Is there any wrong??

2015-11-02 18:46 GMT+08:00 Pascal Landau notifications@github.com:

**Comment by paslandau** [comment]
Did you clone the project or did you require it via composer?

Ususally your composer.json should look like this 

```
{
    "repositories": [ { "type": "composer", "url": "http://packages.myseosolution.de/"} ],
    "minimum-stability": "dev",
    "require": {
         "paslandau/pagerank": "dev-master"
    }
}
```

An then you would run `composer install` in that directory.

**Comment by sam21456789** [comment]
Q1:
I download the entire project ,then I unzip it.
And I follow the step ,   copy and paste the code to the composer.json  .
And I also use  composer install.
Or if it is possible that something wrong on my computer ,like environment
path. etc.

Q2:

{
    "repositories": [ { "type": "composer", "url":
"http://packages.myseosolution.de/"} ],
    "minimum-stability": "dev",
    "require": {
         "paslandau/pagerank": "dev-master"
    }
}

You mean composer.json should contain above code only??

2015-11-02 22:14 GMT+08:00 Pascal Landau notifications@github.com:

**Comment by sam21456789** [comment]
Oh , I just solve the problem.
Thank for your help.

2015-11-02 22:38 GMT+08:00 林長勝 sam21456789@gmail.com:
